# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/middleman
image: registry.gitlab.com/inem/railshurts
# registry.gitlab.com/inem/inem.at:middleman
#

cache:
  paths:
  - .bundle
  - vendor/

stages:
  - test
  - generate
  - deploy

test:
  stage: test
  script:
  - bundle install --path vendor
  - bundle exec middleman build
  except:
    - master

generate:
  stage: generate
  script:
  - bundle install --path vendor
  - bundle exec middleman build
  only:
  - master
  artifacts:
    paths:
      - build

deploy:
  stage: deploy
  script:
  - bundle exec s3_website push
  only:
  - master

check-links:
  stage: deploy
  script:
  - bundle install --path vendor
  - awesome_bot s3_website.yml build/*.html --allow-redirect --allow-dupe