image: registry.gitlab.com/inem/railshurts

cache:
  untracked: true

stages:
  - one
  - two
  - three

generate:
  stage: one
  script:
    - bundle install --path vendor
    - cd lib && ruby config-gen.rb && cd ..
    - bundle exec middleman build
  artifacts:
    paths:
      - build
      - vendor

s3:
  stage: three
  environment: production
  script:
    - bundle install --path vendor
    - bundle exec s3_website push
  only:
    - master

pages:
  image: alpine
  stage: three
  environment: staging
  script:
    - rm -rf public && mv build public
  except:
    - master
  artifacts:
    paths:
    - public

# https://github.com/werk85/node-html-to-text
generate-text:
  image: node
  stage: two
  script:
    - npm install html-to-text -g
    - mkdir -p text
    - cat build/index.html | html-to-text > text/index.txt
    - cat build/principles/index.html | html-to-text > text/principles.txt
    - cat build/mess/index.html | html-to-text > text/mess.txt
    - cat build/team/index.html | html-to-text > text/team.txt
    - cat build/about/index.html | html-to-text > text/about.txt
    - cat build/current_state/index.html | html-to-text > text/current_state.txt
  artifacts:
    paths:
    - text
  dependencies:
    - generate

# https://github.com/btford/write-good
write-good:
  image: node
  stage: three
  script:
    - npm install -g write-good
    - write-good ./text/*.txt
  allow_failure: true
  dependencies:
    - generate-text

# https://github.com/dkhamsing/awesome_bot
awesome-bot:
  stage: three
  script:
    - bundle install --path vendor
    - awesome_bot s3_website.yml build/*.html --allow-redirect --allow-dupe
  allow_failure: true
  dependencies:
    - generate

# https://github.com/hcodes/yaspeller
yaspeller:
  image: node
  stage: three
  script:
    - npm install yaspeller -g
    - yaspeller text/*.txt --ignore-urls --find-repeat-words
  allow_failure: true
  dependencies:
    - generate-text

# https://github.com/mapbox/retext-mapbox-standard
retext:
  image: node
  stage: one
  script:
    - npm install -g retext-mapbox-standard
    - retext-mapbox-standard ./source/*.md.erb
  allow_failure: true

# https://github.com/amperser/proselint
proselint:
  image: python
  stage: three
  script:
    - pip install proselint
    - proselint ./text/*.txt
  allow_failure: true
  dependencies:
    - generate-text
