# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/middleman
image: registry.gitlab.com/inem/railshurts
# registry.gitlab.com/inem/inem.at:middleman
#

cache:
  untracked: true

stages:
  - generate
  - post-generate
  - lint

generate:
  stage: generate
  script:
    - bundle install --path vendor
    - cd lib && ruby config-gen.rb && cd ..
    - bundle exec middleman build
  artifacts:
    paths:
      - build
      - vendor

s3:
  stage: post-generate
  environment: production
  script:
    - bundle install --path vendor
    - bundle exec s3_website push
  only:
    - master

pages:
  image: alpine
  stage: post-generate
  environment: staging
  script:
    - rm -rf public && mv build public
  except:
    - master
  artifacts:
    paths:
    - public

# https://github.com/werk85/node-html-to-text
post-generate:
  image: node
  stage: post-generate
  script:
    - npm install html-to-text -g
    - cat build/index.html | html-to-text > text/index.txt
    - cat build/principles.html | html-to-text > text/principles.txt
    - cat build/mess.html | html-to-text > text/mess.txt
    - cat build/team.html | html-to-text > text/team.txt
    - cat build/about.html | html-to-text > text/about.txt
    - cat build/current_state.html | html-to-text > text/current_state.txt
  artifacts:
    paths:
    - public

# https://github.com/btford/write-good
write-good:
  image: node
  stage: lint
  script:
    - npm install -g write-good
    - write-good ./source/*.md.erb
    - write-good ./source/*.html.haml
  allow_failure: true

# https://github.com/dkhamsing/awesome_bot
awesome-bot:
  stage: lint
  script:
    - bundle install --path vendor
    - awesome_bot s3_website.yml build/*.html --allow-redirect --allow-dupe
  allow_failure: true

# https://github.com/hcodes/yaspeller
yaspeller:
  image: node
  stage: lint
  script:
    - npm install yaspeller -g
    - yaspeller text/*.txt --ignore-urls --find-repeat-words
  allow_failure: true

# https://github.com/mapbox/retext-mapbox-standard
retext:
  image: node
  stage: lint
  script:
    - npm install -g retext-mapbox-standard
    - retext-mapbox-standard ./source/*.md.erb
    - retext-mapbox-standard ./source/*.html.haml
  allow_failure: true

# https://github.com/amperser/proselint
proselint:
  image: python
  stage: lint
  script:
    - pip install proselint
    - proselint ./source/*.md.erb
    - proselint ./source/*.html.haml
  allow_failure: true


