# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/middleman
image: registry.gitlab.com/inem/railshurts
# registry.gitlab.com/inem/inem.at:middleman
#

cache:
  untracked: true

stages:
  - generate
  - post-generate

generate:
  stage: generate
  script:
  - bundle install --path vendor
  - bundle exec middleman build
  artifacts:
    paths:
      - build
      - vendor
      - .bundle

deploy:
  stage: post-generate
  script:
  - bundle install --path vendor
  - bundle exec s3_website push
  only:
  - master

pages:
  stage: post-generate
  script:
  - cp build public
  except:
  - master
  artifacts:
    paths:
    - public

check-links:
  stage: post-generate
  script:
  - bundle install --path vendor
  - awesome_bot s3_website.yml build/*.html --allow-redirect --allow-dupe
  allow_failure: true