# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/middleman
image: registry.gitlab.com/inem/inem.at:middleman
#registry.gitlab.com/inem/railshurts

cache:
  paths:
  - vendor

stages:
  - test
  - deploy

test:
  stage: test
  script:
  - bundle install --path vendor
  - bundle exec middleman build
  except:
    - master

deploy:
  stage: deploy
  script:
  - bundle install --path vendor
  - bundle exec middleman build
  - bundle exec s3_website push
  only:
  - master

check-links:
  stage: deploy
  script:
  - bundle install --path vendor
  - awesome_bot s3_website.yml source/*.md.erb source/*.html.haml source/*.haml --allow-redirect --allow-dupe